### ISSUE TITLE
Missing nullable attribuite on MollieCustomer::isCreditCardSaved doctrine configuration

### ISSUE THREAD

**Issue by markbeazley** [mollie/Sylius#26]
I had an issue upgrading the plugin due to the addition of the is_credit_card_saved column to the mollie_customer table, as it has a NOT NULL constraint but no default value so if you run it on a table that already has records the migraiton fails. Looking at the code the field is marked as a ?string and from what I can see the only values that get set are '1' and null, so I asusme there is a missing nullable="true" from [this line](https://github.com/mollie/Sylius/blob/master/src/Resources/config/doctrine/MollieCustomer.orm.xml#L14)

**Comment by logeecom** [comment]
Hello @markbeazley,

Thank you for reaching out to us regarding this issue.

Please note that our team is taking a look at the reported issue.

As soon as we have more information to provide, we will let you know.

Thank you,

Kind regards.

**Comment by markbeazley** [comment]
@logeecom Thanks, its probably only an issue for people running on a database other than MySql (we use PostgreSQL) so need to generate our own migrations rather than copying/using the ones in the plugin.

**Comment by logeecom** [comment]
Hello @markbeazley,

Note that Molle plugin version [5.7.1](https://github.com/mollie/Sylius/releases/tag/v5.7.1) is live.

This version encompasses a fix for the issue reported in this ticket.

If you have any questions or concerns, feel free to let us know.

Kind regards.
